docusaurus.config.js

テストのPRです、ヘッダーメニューの「Docs」を右に揃えました。
fix header menu position

fix header menu position

---

src/pages/index.tsx

- feat: sync scores from frouriojs/benchmark for 2020-12-06
最新のデータに更新しました。自動更新したいですが、難しそう…
- feat: set chart.fontFamily to inherit
ここだけフォントが違うのも変なので inherit を指定しました

Performance graph の更新・修正

---

src/pages/index.tsx

#12 画面幅が狭い場合に一部のグラフを除外

---

src/pages/index.js

速度グラフのタイトルを「The fastest TypeScript framework」に変更し、下に移動。

レイアウト変更・速度グラフを下に移動

---

.eslintrc.js
.github/workflows/documentation.yml
.prettierrc
babel.config.js
docusaurus.config.js
package.json
sidebars.js
src/components/BrowserWindow/index.tsx
src/pages/index.tsx
yarn.lock

close #24 
- install eslint and prettier
- set up eslint ad prettier
- fix by eslint
- add lint in ci checks

added eslint

---

docusaurus.config.js
package.json
src/css/custom.css
src/libs/markdown.ts
src/pages/changelog.module.css
src/pages/changelog.tsx
yarn.lock

close #17 
<details><summary>show tasks</summary>
I tried remark-twemoji, but it has been unmaintained for a long time, and instead of working as expected, it generated errors.
👇 'Yu Gothic UI'. It's not something cute.
</details>

add changelog page

---

src/css/custom.css

#26 add fallback to Japanese font

---

src/components/CodeBlocks.tsx
src/components/HowtoSetup.tsx
src/pages/index.tsx

fix lint error

---

src/components/CodeBlocks.tsx

add key prop on array map

---

src/pages/index.tsx

ベンチマーク結果の更新（３月分）

---

src/pages/styles.module.css

styles.module.css 内で直書きされていたものを、custom.css 内で定義している css 変数で置き換え

トップページで使用されている色を既存のcss変数に統一

---

src/pages/index.tsx

大変遅くなりました…
最近 commit できておらずすみません……

ベンチマーク更新（4月分）

---

docs/installation/cui.mdx
src/pages/index.tsx

Support options format of over npm v7.
ref: https://docs.npmjs.com/cli/v7/commands/npm-init#forwarding-additional-options
Issue Number: frouriojs/create-frourio-app#236

chore: support npm v7 format

---

package.json
yarn.lock

Docusaurus 2.0.0-rc.1 へ更新 & 依存関係更新

---

docs/reference/addtionalRequest.mdx

fix: typo hook.ts

---

.github/workflows/documentation.yml

chore: update GHA yml

---

src/theme/SiteMetadata/index.js

close #114 
Swizzled 1 component: `SiteMetaData` from `@docusaurus/theme-classic`

#114 add link hreflang tag

---

docs/guide/migration.mdx
sidebars.js

close #133 
`defineController()` 周りについても記載しました。
基本は Changelog (GitHub Release) で、大きな変更や特別な対応が必要なものについてはここに記載する方針です。

#133 Migration Guide を追加

---

docs/reference/validation/zod.mdx

Fix Misspelling

---

docs/guide/index.mdx
docs/reference/index.mdx
docs/reference/routing.mdx
sidebars.js
src/components/DocPageCard/index.tsx
src/components/DocPageCard/styles.module.css
src/components/DocPageCardWrapper/index.tsx
src/components/DocPageCardWrapper/styles.module.css

#146 References・Guides トップページの改善
